### ISSUE TITLE
Sco-ruh

### ISSUE THREAD

**Issue by courtneyfay** [weshebert20/broad-city#4]
the score is SOOO close. I know you can get it workin' raght.

**Comment by weshebert20** [comment]
FINALLY DID IT BY THE GRACE OF GOD HIM(or her) SELF. Actually I created separate variables for both players and then compared who turn it was by clicks (even is Ilana odd is Abbi) and then compared those in the checkForMatch function. It was actually easier once I got rid of a lot of trash code that was confusing the process more.
