### ISSUE TITLE
function function

### ISSUE THREAD

**Issue by courtneyfay** [weshebert20/broad-city#5]
i feel like your code is brilliant and ALMOST but not quite wrapped in functions. if you can change those variables into functions, i do think it will help you solve the score problem (like what we had started to do this afternoon.) GOOD LUCK; YOU'RE GONNA BE GREAT!

**Comment by weshebert20** [comment]
I essentially put both Abbi and Ilana into functions that will add the score and then added those to my checkForMatch function. Thanks Court you have been an actual angel in all of this!
