### ISSUE TITLE
Game allows me to randomly click and flip two different cards

### ISSUE THREAD

**Issue by jpleva91** [weshebert20/broad-city#6]
<img width="943" alt="screen shot 2017-09-29 at 3 55 26 pm" src="https://user-images.githubusercontent.com/17632264/31037547-c0689b74-a52e-11e7-939a-08abeb962412.png">

**Comment by weshebert20** [comment]
from my understanding this was happening when clicking too fast and not allowing the cards to flip back over. It should be fixed now by having the cards flip over faster.
